language: c
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - lib32asound2
      - lib32z1
      - lib32bz2-1.0
      - libssl1.0.0:i386
      - libfreetype6:i386
before_script: 
  - git clone --depth=1 https://github.com/estebanlm/pharo-travis-ci.git
  - cp lib/$TRAVIS_OS_NAME/* .
script:
  - pharo-travis-ci/run-tests.sh
env: 
  global: 
    - baseline="TokyoDB"
    - packages_dir="mc"
    - pharo_version="50"