language: smalltalk
sudo: false
smalltalk: Pharo-5.0
before_script: scripts/build-tokyocabinet.sh
addons:
  apt:
    packages:
      - libc6-dev:i386
      - zip:i386
      - bzip2:i386
      - zlib1g:i386
      - zlib1g-dev:i386
      - build-essential
      - gcc-multilib
      - g++